# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectedSong.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from SongDetails import SongsDetails
from Songs import Songs_array
from homePageHisUI import *
from recommenderEngine import engine


class Ui_mainSelectedSong(object):
    def ratingFilledStars(self):
        self.star1.setStyleSheet(
            "qproperty-icon: url(filledStar.png);"
            "background-color:transparent;"
        )
        for i in range(1, 5):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(emptyStar.png);"
                "background-color:transparent;"
            )
        self.rating = 1

    def ratingFilledStars2(self):
        for i in range(0, 2):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(filledStar.png);"
                "background-color:transparent;"
            )
        for i in range(2, 5):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(emptyStar.png);"
                "background-color:transparent;"
            )
        self.rating = 2

    def ratingFilledStars3(self):
        for i in range(0, 3):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(filledStar.png);"
                "background-color:transparent;"
            )
        for i in range(3, 5):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(emptyStar.png);"
                "background-color:transparent;"
            )
        self.rating = 3

    def ratingFilledStars4(self):
        for i in range(0, 4):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(filledStar.png);"
                "background-color:transparent;"
            )
        for i in range(4, 5):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(emptyStar.png);"
                "background-color:transparent;"
            )
        self.rating = 4

    def ratingFilledStar5(self):
        for i in range(0, 5):
            self.stars[i].setStyleSheet(
                "qproperty-icon: url(filledStar.png);"
                "background-color:transparent;"
            )
        self.rating = 5

    def logoutUser(self, MainWindow):
        self.recommender.saveData()
        print('data saved')
        from login import Ui_MainWindow
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.selectedPage.hide()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()

    def __init__(self, message, user, recommender):
        self.message = message
        self.user = user
        self.recommender = recommender
        self.currSongId = recommender.getSongID(self.message)
        self.songData = recommender.getSongData(self.currSongId)
        self.albumName = self.songData
        # self.recommender.loadData()
        # print('current song:' + message)
        # print('user retrieved: ' + user)
        # print(('current album: ' + str(self.albumName[2])))
        # if message in Songs_array:
        #     print(message.artist)
        for x in Songs_array:
            if x.title == message:
                print(x.artist)
                self.artist = x.artist
        self.rating = 0

    def setupUi(self, mainSelectedSong):
        mainSelectedSong.setObjectName("mainSelectedSong")
        mainSelectedSong.resize(800, 600)
        self.selectedPage = mainSelectedSong
        self.centralwidget = QtWidgets.QWidget(mainSelectedSong)
        self.centralwidget.setObjectName("centralwidget")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(-10, 0, 91, 51))
        self.back_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.back_btn.setAutoFillBackground(False)
        self.back_btn.setStyleSheet("\n"
                                    "border-radius:10px;\n"
                                    " image: url(D:/College Stuff/Semester 8/Artificial Intelligence/FinalAI/next.png);")
        self.back_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("next-white.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn.setIcon(icon)
        self.back_btn.setIconSize(QtCore.QSize(32, 32))
        self.back_btn.setCheckable(False)
        self.back_btn.setObjectName("back_btn")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(550, 10, 121, 41))
        self.label_username.setStyleSheet("background-color:#65D36E;\n"
                                          "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                          "border-radius:10px;\n"
                                          "text-align: center;\n"
                                          "color: bkack;\n"
                                          "font-weight: bold;")
        self.label_username.setAlignment(QtCore.Qt.AlignCenter)
        self.label_username.setObjectName("label_username")
        self.logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logout_btn.setGeometry(QtCore.QRect(690, 10, 93, 41))
        self.logout_btn.setStyleSheet("border:1px solid white;\n"
                                      "border-radius:10px;\n"
                                      "color:white;")
        self.logout_btn.setObjectName("logout_btn")
        self.logout_btn.clicked.connect(self.logoutUser)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 120, 351, 281))
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet("background-color:#000000;")
        self.pushButton_12.setText("")
        self.pushButton_12.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_12.setObjectName("pushButton_12")
        self.songTitle_label = QtWidgets.QLabel(self.centralwidget)
        self.songTitle_label.setGeometry(QtCore.QRect(420, 110, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.songTitle_label.setFont(font)
        self.songTitle_label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
                                           "font-weight:bold;\n"
                                           "color:white;")
        self.songTitle_label.setObjectName("songTitle_label")
        self.artistName_label = QtWidgets.QLabel(self.centralwidget)
        self.artistName_label.setGeometry(QtCore.QRect(420, 160, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.artistName_label.setFont(font)
        self.artistName_label.setObjectName("artistName_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 190, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.star5 = QtWidgets.QPushButton(self.centralwidget)
        self.star5.setGeometry(QtCore.QRect(490, 270, 31, 16))
        self.star5.setStyleSheet("\n"
                                 "background-color:transparent;")
        self.star5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("emptyStar.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.star5.setIcon(icon1)
        self.star5.setObjectName("star5")
        self.star3 = QtWidgets.QPushButton(self.centralwidget)
        self.star3.setGeometry(QtCore.QRect(450, 270, 31, 16))
        self.star3.setStyleSheet("\n"
                                 "background-color:transparent;")
        self.star3.setText("")
        self.star3.setIcon(icon1)
        self.star3.setObjectName("star3")
        self.star1 = QtWidgets.QPushButton(self.centralwidget)
        self.star1.setGeometry(QtCore.QRect(410, 270, 31, 16))
        self.star1.setStyleSheet("\n"
                                 "background-color:transparent;")
        self.star1.setText("")
        self.star1.setIcon(icon1)
        self.star1.setObjectName("star1")
        self.star4 = QtWidgets.QPushButton(self.centralwidget)
        self.star4.setGeometry(QtCore.QRect(470, 270, 31, 16))
        self.star4.setStyleSheet("\n"
                                 "background-color:transparent;")
        self.star4.setText("")
        self.star4.setIcon(icon1)
        self.star4.setObjectName("star4")
        self.star2 = QtWidgets.QPushButton(self.centralwidget)
        self.star2.setGeometry(QtCore.QRect(430, 270, 31, 16))
        self.star2.setStyleSheet("\n"
                                 "background-color:transparent;")
        self.star2.setText("")
        self.star2.setIcon(icon1)
        self.star2.setObjectName("star2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 831, 71))
        self.label.setStyleSheet("background-color: #000000;\n"
                                 "border-color:white")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(-20, -50, 831, 651))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("ai-background.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.albumName_label = QtWidgets.QLabel(self.centralwidget)
        self.albumName_label.setGeometry(QtCore.QRect(420, 220, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.albumName_label.setFont(font)
        self.albumName_label.setObjectName("albumName_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 331, 261))
        self.label_2.setStyleSheet("border-radius:15px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("song-bg.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_11.raise_()
        self.label.raise_()
        self.back_btn.raise_()
        self.label_username.raise_()
        self.logout_btn.raise_()
        self.pushButton_12.raise_()
        self.songTitle_label.raise_()
        self.artistName_label.raise_()
        self.label_3.raise_()
        self.star5.raise_()
        self.star3.raise_()
        self.star1.raise_()
        self.star4.raise_()
        self.star2.raise_()
        self.albumName_label.raise_()
        self.label_2.raise_()
        mainSelectedSong.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainSelectedSong)
        QtCore.QMetaObject.connectSlotsByName(mainSelectedSong)
        self.back_btn.clicked.connect(self.goToHomePageHis)
        self.star1.clicked.connect(self.ratingFilledStars)
        self.star2.clicked.connect(self.ratingFilledStars2)
        self.star3.clicked.connect(self.ratingFilledStars3)
        self.star4.clicked.connect(self.ratingFilledStars4)
        self.star5.clicked.connect(self.ratingFilledStar5)
        self.stars = [self.star1, self.star2,
                      self.star3, self.star4, self.star5]
        self.recommender.buildRatingMatrix()

    def goToHomePageHis(self, homePageHisWindow):
        get_username = self.user
        get_song_name = self.message
        get_rating = self.rating
        self.homePageHisWindow = QtWidgets.QMainWindow()
        self.username = get_username
        self.message = get_song_name
        self.songRating = get_rating
        self.ui = Ui_homePageHisWindow(
            self.message, self.username, self.songRating, self.recommender)
        self.ui.setupUi(self.homePageHisWindow)
        self.selectedPage.hide()
        self.homePageHisWindow.show()
        # print('rating lagunya: ' + str(self.rating))
        # print('lagu yang dipilih: ' + self.message)
        self.recommender.saveData()

    def retranslateUi(self, mainSelectedSong):
        _translate = QtCore.QCoreApplication.translate
        mainSelectedSong.setWindowTitle(
            _translate("mainSelectedSong", "MainWindow"))
        self.label_username.setText(_translate("mainSelectedSong", self.user))
        self.logout_btn.setText(_translate("mainSelectedSong", "LOGOUT"))
        self.songTitle_label.setText(
            _translate("mainSelectedSong", self.message))
        self.artistName_label.setText(
            _translate("mainSelectedSong", self.artist))
        self.label_3.setText(_translate("mainSelectedSong", "Album:"))
        self.albumName_label.setText(
            _translate("mainSelectedSong", self.albumName[2]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainSelectedSong = QtWidgets.QMainWindow()
    ui = Ui_mainSelectedSong()
    ui.setupUi(mainSelectedSong)
    mainSelectedSong.show()
    sys.exit(app.exec_())
